### ISSUE TITLE
Vagrantfile for Comprehensive Review

### ISSUE THREAD

**Issue by pilasguru** [ceso/rhcl#1]
Dear @ceso 

I have this repo at gitlab 
https://gitlab.com/pilasguru/RHCSA-RHCE
to create platform to follow the _comprensive review_ only.

I have just opened it to clone and pull-request if you with to give a hand.

Happy 2K17 !
@pilasguru

**Comment by ceso** [comment]
Hi, @pilasguru thanks for that, I've been working in improve the recipes I wrote (and continous in that), currenly I replicated sometthing near to an entire lab, but still is a lot of work for to do, because I want to write recipes for install everything related to the lab (for install libvirt to the play with lab).

Regards!
Ceso.
